[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

allow_paths = ["./lib"]

remappings = [
    '@openzeppelin=lib/openzeppelin-contracts/contracts',
    '@ccip/=lib/ccip/',
    '@chainlink/local/=lib/chainlink-local/'
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"
zksync = "${ZKSYNC_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
